// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT8Ry7bfCTCJ2Gu0xLr0NsqpZzqq64cow',
    appId: '1:216452483556:web:244e6e18d1b63331425ff1',
    messagingSenderId: '216452483556',
    projectId: 'mj-cuisine',
    authDomain: 'mj-cuisine.firebaseapp.com',
    storageBucket: 'mj-cuisine.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXQsAwTwXnkGzqqp415VrchEFu35gcB70',
    appId: '1:216452483556:android:de43bf3b8bea6547425ff1',
    messagingSenderId: '216452483556',
    projectId: 'mj-cuisine',
    storageBucket: 'mj-cuisine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXPyaUdYEDo6d4VjHZvvW6rvAB3Ozbz0I',
    appId: '1:216452483556:ios:24e97d0a009cc522425ff1',
    messagingSenderId: '216452483556',
    projectId: 'mj-cuisine',
    storageBucket: 'mj-cuisine.appspot.com',
    iosClientId: '216452483556-0bdusnl5mgmfisvggrec0sr930m97868.apps.googleusercontent.com',
    iosBundleId: 'com.example.shp2',
  );
}
